Gradient outlines part 1
LLK/scratch-paint pull request #1166
Opened 2020-07-09 22:03 UTC by adroitwhiz

### Resolves

A step towards https://github.com/LLK/scratch-paint/issues/540

### Proposed Changes

This PR implements the "refactoring" half of the "gradient outlines" changes--this should contain no functional changes but cleans up the codebase in preparation for adding gradient outline support.

### Reason for Changes

See above

### Test Coverage

Tests have been updated accordingly

2020-07-13 19:59 UTC, fsih requested changes
Thanks for splitting all this out, it helps a lot!

I ran into an issue where if you select a shape with a hole, and set the fill to a gradient, then the fill becomes transparent:
<img width="411" alt="Screen Shot 2020-07-13 at 15 55 33" src="https://user-images.githubusercontent.com/2855464/87347838-d8327700-c521-11ea-93fd-8b58b750ad9b.png">

2020-07-13 20:07 UTC, fsih commented
Here's the same SVG exported from scratch.mit.edu vs exported from the gradient-outlines branch: https://www.diffchecker.com/xGHcgGmX

2020-07-20 19:29 UTC, fsih submitted a review, later dismissed
LGTM!

2020-07-20 19:29 UTC, fsih commented on src/helper/style-path.js
> +    return colorState;
Can we document the params of the return value, and note that gradientType may be null?

2020-07-23 10:22 UTC, adroitwhiz commented
I've changed `applyGradientTypeToSelection` to call `createGradientObject` when creating gradients-- this is important in part 2 when we change `createGradientObject` to enforce a minimum distance between the gradient start and end points (this fixes perfectly vertical gradients on perfectly horizontal lines, or vice versa, from disappearing).

2020-07-24 17:14 UTC, fsih approved these changes
LG!

2020-07-28 20:46 UTC, merged