Implement GH-41: Add minimum width gui
LLK/scratch-paint pull request #194
Opened 2017-11-07 20:30 UTC by mewtaylor

This implements #41. It adds a new component, `Dropdown`, which is a formatted version of the `Popover` element.

I also moved the `modes.js` file to a `lib` folder, and added `layout-constants` from gui to the lib folder as well. This move from `modes/modes.js` to `lib/modes.js` can be reverted if needed.

@carljbowman and I discussed using the `ContextMenu` for this, however that library is pre-built to pop up wherever there is a click, which is not the desired behavior for this feature.

We could feasibly move the styling for `.mod-menu-item` into its own component on dropdown if we want, but I wasn't sure if that was a good idea or not.

2017-11-07 20:41 UTC, rschamp commented on package.json
> +    "react-responsive": "^3.0.0",
We should pin this since it's actively used by the application

2017-11-08 20:14 UTC, fsih requested changes

2017-11-08 20:14 UTC, fsih commented on src/lib/layout-constants.js
> +    fullSizeMinWidth: 1096
This one says 1096 and the other one says 1095. Is that right?

2017-11-08 20:14 UTC, fsih commented on src/components/paint-editor/paint-editor.jsx
> -    onPasteFromClipboard: PropTypes.func.isRequired,
I think you want to add these back too

2017-11-08 20:14 UTC, fsih commented on src/components/paint-editor/paint-editor.jsx
> +                                    onCopyToClipboard={this.props.onCopyToClipboard}
Nit: there are some extra spaces here

2017-11-08 20:14 UTC, fsih commented on src/lib/layout-constants.js
> +    fullSizeMinWidth: 1096
Also noticed that things stick out a bit before min width UI kicks in, so we might want to do it sooner?
![image](https://user-images.githubusercontent.com/2855464/32572067-772ac6fc-c497-11e7-8352-5f29562058d1.png)

2017-11-08 21:38 UTC, fsih commented
If the 1096/1095 difference is intentional, then this PR looks good to me

2017-11-09 16:59 UTC, fsih submitted a review, later dismissed

2017-11-20 16:40 UTC, paulkaplan commented
@fsih I think this requires your re-review.

2017-11-20 17:03 UTC, fsih approved these changes
Sorry! Thanks for the reminder ping

2017-11-21 16:06 UTC, merged