Use sans-serif font in playground
LLK/scratch-paint pull request #264
Opened 2018-01-21 10:53 UTC by heyitsmeuralex

Caused some cascade issues where you'd see default fonts in components (i.e. serif). This is only for the playground as, I imagine, in scratch-3.0 this font style would be inherited.

Before (firefox-linux):
![image](https://user-images.githubusercontent.com/9429556/35193378-5eed40b0-fe99-11e7-8a90-9e53efaafe82.png)

After:
![image](https://user-images.githubusercontent.com/9429556/35193375-54523430-fe99-11e7-9316-0daffe35a0ca.png)

2018-01-22 18:41 UTC, fsih requested changes
Thanks! Can you just format it by adding newlines after <style> and before </style> and indentation and spaces in the style of our .css files, such as https://github.com/LLK/scratch-gui/blob/0e56f866e5a4a736f7e618571fc64315a015fea3/src/index.css ?

2018-03-26 16:08 UTC, thisandagain commented
Closing due to lack of activity.

2018-03-26 16:12 UTC, heyitsmeuralex commented
@thisandagain oops, I forgot about this! Should have fixed the style now.

2018-04-02 15:00 UTC, fsih approved these changes
Looks good, thanks!

2018-04-02 15:00 UTC, merged