Fix editorconfig indentation rules
LLK/scratch-paint pull request #339
Opened 2018-03-26 16:21 UTC by heyitsmeuralex

Rules before:

* 4-wide tabs everywhere, except
* .js and .html files, using 4 spaces **(note this project also uses .ejs & .jsx files which are not covered by this!)***

Changed in this PR to:

* 4 spaces everywhere (ie. including .jsx and .ejs files), except
* .yml files, using 4-wide tabs
* .json files (eg. package.json), using 2 spaces (may want to change package.json to use 4sp?)

Also fixed index.ejs to use 4 spaces instead of two.

2018-03-26 18:54 UTC, thisandagain commented
Thanks @heyitsmeuralex !

2018-04-02 15:27 UTC, fsih requested changes
The .editorconfig file matches our other repos (e.g. scratch-gui, scratch-vm) so maybe it would make sense to leave them consistent, or change all the repos at the same time?

I think this makes sense, except I don't think we should use tabs for indentation anywhere. Can you switch .yml to 2 space indentation? Thanks!

2018-04-03 00:10 UTC, heyitsmeuralex commented
@fsih done as you said :)

2018-04-03 14:31 UTC, fsih approved these changes
Cool, thanks!

2018-04-03 14:31 UTC, merged