Double resolution of canvas
LLK/scratch-paint pull request #386
Opened 2018-04-17 15:13 UTC by fsih

### Resolves

Part of work for supporting Scratch 2's double resolution bitmaps

### Proposed Changes

Double the resolution of the canvas

2018-04-19 19:05 UTC, paulkaplan requested changes
A few cleanup things are needed here.

2018-04-19 19:05 UTC, paulkaplan commented on src/helper/view.js
> +    paper.project.view.zoom = .5;
I think you also need to change the `math.max` line to be with 0.5 instead of 1 on line 28; zooming out is stuck at half zoom, can't zoom all the way out.

2018-04-19 19:05 UTC, paulkaplan commented on src/containers/paint-editor.jsx
> +            isBitmap(this.props.format)
Looks like this is an extra line from a different branch?

2018-04-19 19:05 UTC, paulkaplan commented on src/containers/paper-canvas.jsx
> +                document.body.appendChild(subCanvas);
Doesn't look like this should be here!

2018-04-20 15:18 UTC, fsih commented on src/helper/view.js
> +    paper.project.view.zoom = .5;
Good catch, thanks!

2018-04-20 15:19 UTC, fsih commented on src/containers/paint-editor.jsx
> +            isBitmap(this.props.format)
Done

2018-04-20 15:20 UTC, fsih commented on src/containers/paper-canvas.jsx
> +                document.body.appendChild(subCanvas);
Haha, it's a feature!

2018-04-20 15:36 UTC, paulkaplan approved these changes
LG

2018-04-20 15:38 UTC, merged